### ISSUE TITLE
Measure Satellite Spot Flux primitive IDL error

### ISSUE THREAD

**Issue by briley-lewis** [geminiplanetimager/gpi_pipeline#113]
I was going through the GPI pol tutorial and encountered an error when trying to run the Measure Satellite Spot Flux primitive as part of the Simple Polarization Data Cube Extraction recipe for creating podc files. The error when setting verbose=1 in the primitive is:

`Tag name SECONDORDER is undefined for structure <Anonymous> % Execution halted at: GPI_MEASURE_SATELLITE_SPOT_FLUX_POL  106`

**Comment by rjderosa** [comment]
Thanks for the bug report! I reduced a random J-band polarimetry image from the archive and it got past this step without any error (I'm on revision c0cad3f). It might be related to the specific data you are using. If you could share the file name I could try again with the same file you are using to try to reproduce the error. A copy of the failed xml file from the Queue directory would be helpful, as well as a copy of the log in Reduced/logs.

**Comment by briley-lewis** [comment]
I just installed it last week, the last commit when I run git log is
"515a74967a64423db203261e7f2635075f5de477" and there was no "failed" xml
file produced it seems. Basically it froze up my computer and the whole
pipeline interface once the primitive failed and I had to force quit
everything. Logs are attached from the 2 days I tried it. I'm using the
data set given in the pol tutorial:
http://docs.planetimager.org/pipeline/usage/tutorial_pol.html

**Comment by briley-lewis** [comment]
Logs are here!
[gpi_drp_200805.log](https://github.com/geminiplanetimager/gpi_pipeline/files/5043016/gpi_drp_200805.log)
[gpi_drp_200804.log](https://github.com/geminiplanetimager/gpi_pipeline/files/5043017/gpi_drp_200804.log)

**Comment by rjderosa** [comment]
Thanks for posting the logs. I don't see the failure here unfortunately. I did try reducing the tutorial data on my pipeline and things worked okay. Would you mind running the "rescan calib DB" and "rescan DRP config" and then trying the tutorial again? If it continues to crash could you share the newer log I can try to debug more.

**Comment by briley-lewis** [comment]
Yep, Pauline just messaged me and suggested trying rescan DRP config - that
fixes it!

**Comment by rjderosa** [comment]
Great!
