### ISSUE TITLE
Develop code for empirical measurement of microlens PSFs

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#14]
8) Data Cube Extraction
Inversion algorithm now implemented in pipeline form.  Using microlens PSF.
right now using simulated microlens PSFs from DST
works on real data already. 
Next to do is to measure microlens PSF from real data. Jerome working on now. 
- Action: Jerome, Marshall, Christian to discuss microlens PSF extraction early next week

**Comment by dsavransky** [comment]
Recovering rm journals for issue:

mperrin: IN progress by Marshall. 

mperrin: Update to note that JB is leading this, with Patrick. 

ingraham: This is working very well now, but it's been determined that we're resolving the filter profile in H and K bands (haven't checked the others, but Y is nearly impossible, J is unlikely).

Next step is to implement a deconvolution in the final step before outputting the image. Option #2 is to buy a monochromator and take new data. Rumour has it Anand has one...

**Comment by mperrin** [comment]
Legacy issue migrated from redmine issue tracker. Originally filed by @mperrin on 2012-11-30

I don't think this very old issue serves any useful purpose at this point. See 2014 SPIE paper by @pi11235 among other things.
