### ISSUE TITLE
Destripe channel boundary offset drifts

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#17]
Channel bias subtraction for the 32 readout channels

```
  * Basic linear subtraction already done based on reference pixels by detector server
  * start with Patrick's existing code in destriping routine (also does a linear fit to each channel)
```

Low priority but should be relatively straightforward. Obvious correlated noise to the eye, therefore should be fixed.

**Comment by mperrin** [comment]
Legacy issue migrated from redmine issue tracker. Originally filed by @mperrin on 2013-03-07

Closely related to #21 
As @pi11235 said on that one "close it. we're not detector noise limited anyways...."
