### ISSUE TITLE
thermal background subtraction in cube space

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#20]
Due to the fact that K band observations will not be performed in a traditional nodding sequence (most likely), flexure compensation will be important when subtracting the background therefore requiring the calibration be done in cube space and not in detector space.

This can probably be completed using a modified version of " Interpolate spectal datacube" with a different suffix and the writing of the file to calibration directory. Implementing this will also require a new Subtract thermal/sky background that works in cube space.

**Comment by mperrin** [comment]
Legacy  issue migrated from redmine issue tracker. Originally filed by @pi11235 

This was flagged as "work in progress" on the old tracker, but actually isn't this functionality pretty much working now? @abhijithrajan you've done a lot of work with the K band data now. Do you have any opinion about the state of this code and if it's good enough?

**Comment by semaphoreP** [comment]
I'm pretty sure this has been working for a while now so we should close it

**Comment by abhijithrajan** [comment]
^ Agreed
