### ISSUE TITLE
Improved channel bias offset removal in dark images

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#21]
Currently, there is no channel bias offset removal in destripe for darks.

I think this is something that should be implemented no? Unless the bias is changing around some mean, in which case removing the bias would remove the mean.  Ideally, I think we want to perform a channel bias correction in every science and dark frame...

... someone please correct me if my logic is flawed...

**Comment by mperrin** [comment]
Legacy issue migrated from redmine issue tracker.  Originally filed by @pi11235 in 2013 pre first light. 
I believe there is no motivation for improving any of this code right now. 

@pi11235 @jchilcote do you concur we can close this issue?

**Comment by patrickingraham** [comment]
close it. we're not detector noise limited anyways....
