### ISSUE TITLE
Quicklook hour-long sequence template

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#22]
Create template that includes: Accumulate Images, Align & Derotate (new primitive), Median Combine (ADI) datacubes - perhaps rename this last primitive so it is more general.  This replaces feature request 132.  Original request:

For very fast QL of long sequences, GPItv could open a long sequence of images, do an image registration using the spots, rotate to North up and median combine for each wavelength of the cube. This would allow us to rapidly estimate the quality of long sequences, see if we can see faint planets, etc.

This will be implemented as a pipeline template which will automatically open the results in GPItv.

**Comment by mperrin** [comment]
Legacy issue migrated from redmine issue tracker. No action desired at this time.

issue originally filed by @dsavransky in 2013, pre first light. Functionality now provided by GPIES Data Cruncher and related QL tools.
