### ISSUE TITLE
Queue Viewer should have select-by-time-range to ignore old recipes

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#23]
New feature for Queue Viewer: It should have an option (enabled on a menu?) to just display today's recipes, versus all recipes. This should be enabled by default. This will let the queue viewer tool become useful again, without having to enforce periodic deletion of completed recipes. 

It will be important to implement this in such a way that it looks at just filesystem date stamps, not dates or directories in the recipes themselves. This means it can avoid having to parse the XML slowly for thousands of old files you don't care about.

**Comment by dsavransky** [comment]
Recovering rm journals for issue:

mperrin: Nobody is really using the Queue Viewer much. Setting this to lowest priority.  We could consider just closing this issue entirely.

**Comment by dsavransky** [comment]
Recovering rm journals for issue:


mperrin: Nobody is really using the Queue Viewer much. Setting this to lowest priority.  We could consider just closing this issue entirely.

**Comment by mperrin** [comment]
No one ever uses the Queue Viewer so there is no reason to spend effort on this.
