### ISSUE TITLE
Create an unbiased polarized intensity map

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#33]
Linear Polarization Intensity is biased. 

It would be great to have a primitive to create an unbiased linear polarization intensity image. 

Here's a good reference:
http://adsabs.harvard.edu/abs/2006PASP..118.1340V

**Comment by mperrin** [comment]
Legacy issue migrated from redmine issue tracker. Originally filed by @maxwellmb on 2014-05-06

The radial stokes code subsequently implemented by @maxwellmb is a better way of doing this anyway, so we can close this issue.
