### ISSUE TITLE
Option to save the contrast measurement in the "Measure Contrast" primitive

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#35]
A similar request has been sent and was complete for the GPItv :  it would be nice to have the options to save the contrast as a txt file.
Thank you!

**Comment by mperrin** [comment]
Legacy issue migrated from redmine issue tracker. Originally filed by Pascale Hibon on 2014-07-03

The existing capabilities for saving contrast as FITS files seems like it's working well enough two years later so I'm going to close this.
