### ISSUE TITLE
Propagation of DQ frames through the pipeline

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#38]
Jeff to coordinate, lots of other people to contribute. 

Goal of by the _second year_ of the campaign, having all the pipeline propagate DQ frames so that we get DQ data cubes out in the end that warn of any potential artifacts or problems at a pixel level. 

Worth thinking about UNCERT extensions as well but that's a much harder problem to do well.

**Comment by dsavransky** [comment]
Recovering rm journals for issue:

mperrin: Updating this to reflect the fact that it's in progress by Kate and Patrick.  I have no idea what the right percent progress is, so I just hand waved 50%. 

ingraham: Currently have the DQ frames propagating through the spec cube and pol cube creation. The next steps are require some decisions on how to handle the DQ frames for cube creation etc. Kate will discuss this during her mini-presentation.

mperrin: Progress made in the spring, then stalled out. Might as well include what's done so far in release 1.4, but it's incomplete. 

kfollette: dq frames are propagating through to podc and spdc cubes, but not beyond. not clear to what extent these are being used so far, so we should have a broader discussion about how/whether to proceed from here.

**Comment by semaphoreP** [comment]
Should we close this issue? It seems DQ frames are being propagated to the end products of the pipeline (i.e. data cubes). @kfollette @mperrin

**Comment by kfollette** [comment]
yes, I'm comfortable with that. It's been working pretty seamlessly throughout the past few runs

**Comment by maxwellmb** [comment]
I haven't checked, but is it working in Pol mode? If not we might want to
keep it open, or create a separate issue to get it going there.

**Comment by kfollette** [comment]
Yep also working in pol mode through creation of podc cubes

**Comment by semaphoreP** [comment]
Excellent, it is closed! Thanks all!
