### ISSUE TITLE
Reimplement Make Data Log File tool

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#44]
The 'Make Data Log File' tool is essentially never used and is probably not needed. It has several problems as described below, however it is low priority to fix these, so instead we're disabling this function for now. 

It does work to output a text log file, however:
- the column widths are not wide enough for the new Gemini-format keyword values like "DISP_PRISM_G1234". Columns should be wider or (better solution) only the short & friendly value names should be printed
- after the script runs, the window does not close. In fact a tiny little blank gray window is create for no apparent reason and that sticks around forever too.
- it ought to pop up some dialog that says "File successfully written to so-and-so.txt"

**Comment by mperrin** [comment]
Legacy Rejected/wontfix issue migrated from redmine issue tracker. No action desired at this time.
