### ISSUE TITLE
Better pipeline-produced filenames for output files

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#46]
There should be better filenames for the output files. 

e.g. instead of darks0003-darks.fits we should get darks_120323_0003_1.45s-darks.fits, or something like that.  What that default filename is could depend on what type of file is being written (e.g. FILETYPE keyword). Alternatively we use the gemini data label keyword?  And there will probably need to be some configuration file options to define this behavior.

**Comment by mperrin** [comment]
Legacy Rejected/wontfix issue migrated from redmine issue tracker. No action desired at this time.
