### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#47]
---

Scan Dir opening in GPItv: /mnt/ifs/Detector//120330/extu0001.fits
% Attempt to subscript <PtrHeapVar388732> with <LONG     (         276)> is
   out of range.
% Execution halted at: GPITV::GETTRACK  4406
   /home/LAB/IDL/gpitv/gpitv__define.pro
%                      GPITV::REFRESH   2887
   /home/LAB/IDL/gpitv/gpitv__define.pro
%                      GPITV::DISPLAYALL 2846
   /home/LAB/IDL/gpitv/gpitv__define.pro
%                      GPITV::LOAD_NEW_IMAGE 5408
   /home/LAB/IDL/gpitv/gpitv__define.pro
%                      GPITV::READFITS  5288
   /home/LAB/IDL/gpitv/gpitv__define.pro
%                      GPITV::OPEN      5183
   /home/LAB/IDL/gpitv/gpitv__define.pro
%                      DIRVIEWER::VIEW_IN_GPITV 1250
   /home/LAB/IDL/gpitv/dirviewer__define.pro
%                      DIRVIEWER::UPDATE  837
   /home/LAB/IDL/gpitv/dirviewer__define.pro
%                      DIRVIEWER::HIGHLIGHT_SELECTED  667
   /home/LAB/IDL/gpitv/dirviewer__define.pro
%                      DIRVIEWER::REFRESH  618
   /home/LAB/IDL/gpitv/dirviewer__define.pro
%                      DIRVIEWER::EVENT  166
   /home/LAB/IDL/gpitv/dirviewer__define.pro
%                      DIRVIEWER_EVENT    88
   /home/LAB/IDL/gpitv/dirviewer__define.pro
%                      WIDGET_PROCESS_EVENTS
%                      $MAIN$

**Comment by mperrin** [comment]
Legacy Rejected/wontfix issue migrated from redmine issue tracker. No action desired at this time.
