### ISSUE TITLE
drfgui: better handling of save file names

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#49]
The current way the filenames are auto-generated for the DRFGUI based on the current time is not very user friendly. Specifically, if you try to resave a file a second time even without making any edits, because the filename is derived from the time the second save will go to a new filename. This is not how users expect File | Save to work in pretty much any other application. You should have to select File | Save As... in order to change the filename. The regular File | Save option should always reuse the last used filename.

**Comment by semaphoreP** [comment]
Isn't DRFGUI deprecated? Current GPI DRP save behavior does not behave like this so should not be an issue.

**Comment by mperrin** [comment]
DRFGUI is now called the Recipe Editor but it's the same code base (years later and variously improved)

Thanks for the housekeeping on all these @semaphoreP
