### ISSUE TITLE
Figure out how to write a good automated installer on Windows. 

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#52]
Should have a one-click automated installer type of thing for Windows. Assume the user has already successfully installed IDL Runtime (or can we include that as part of our installer too?). Should download the zip files, unzip to a directory of the user's choosing (Default = C:\Program Files\GPI ? ), then set up an item on the start menu, etc. THis would be pretty cool...  Can we get some Gemini programmer to help this?

**Comment by mperrin** [comment]
Legacy Rejected/wontfix issue migrated from redmine issue tracker. No action desired at this time. 

And  @semaphoreP took care of this for us a year or two ago anyway!
