### ISSUE TITLE
Improved configuration file parsing. 

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#53]
Use someone else's prewritten parser for config files. Allow comments on the same line as values? Perhaps an "INI" format structured text file with different sections?

See discussion thread at https://groups.google.com/forum/?fromgroups#!topic/comp.lang.idl-pvwave/ypj5JBGzYlY

the gm_read_textstructure here looks pretty good: http://hrscview.fu-berlin.de/idl.html

But, well, fundamentally what we have now is working well enough for current purposes. Low priority to improve.

**Comment by semaphoreP** [comment]
The configuration files are simple enough that custom code is fine. No need to spend more time on this.
