### ISSUE TITLE
"prompt_user_for_questionable_data" setting

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#54]
New configuration file setting to control whether users are queried via a pop up dialog for questionable files (aborted/lousy seeing/otherwise marked as low DQ, etc), or are they just silently discarded

**Comment by semaphoreP** [comment]
This pop-up dialog either doesn't exist or is very infrequently triggered. Regardless, this doesn't seem like a feature that needs to be implemented right now. Perhaps in the future, we can query the database for bad files, but that is out of the scope of this issue.
