### ISSUE TITLE
gpi-pipeline script fails on machines lacking an 'xterm' command

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#56]
Some machines for some reason don't have 'xterm' in the path to invoke a new terminal window, so the gpi-pipeline script fails. Can we make it fail more gracefully, and possible fall back to try some other commands to launch new terminals?

**Comment by semaphoreP** [comment]
xterm is pretty easy to install. There are also other ways to start the DRP without using the gpi-pipeline script. Closing this unless it becomes a bigger issue.
