### ISSUE TITLE
Pipeline should be able to write PNG images for ADI sequence results

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#58]
Fredrik wants at Gemini, for the pipeline to produce a PNG or JPG image of the reduced sequence that could be emailed out to users in their "you have new data" email. Simple PNG of the collapsed cube, with the datalabel, filter, etc overlaid as text. 

Thus implement a new primitive "Export FITS to Image" that can write a PNG or JPEG. Gets saved to output directory with the same filename as the image would be, except the extension is different.

**Comment by mperrin** [comment]
Legacy Rejected/wontfix issue migrated from redmine issue tracker. No action desired at this time. 

Gemini is never going to actually use this capability - they're not even archiving the summit QL cubes so they have no way of using the PNGs in emails to users. For GPIES internal purposes the Data Cruncher and Files DB preview images meet this need.
