### ISSUE TITLE
Automatic Reducer should have some ability to process sequences

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#59]
Per Fredrik: For night time use at Gemini, usually looking at quicklook images one at a time is what is wanted (track AO performance over time as you take data, etc).  But sometimes you would want to reduce the whole sequence to a PSF-suppressed cube.  You could do this using the data parser, but we could also give a little bit of this functionality to the automatic reducer tool. Select multiple images, then press Reprocess, and it would run a new "Quicklook Sequence" recipe template that does some basic ADI combination?

TBD exactly how this ought to work. Let's discuss.

**Comment by semaphoreP** [comment]
Automated PSF subtraction exists for GPIES and happens in real time. For non-campaign users, ADI routines exist in the GPI DRP Recipe Editor, so they can go there and reduce it if they really want to. Currently, it seems this is a lot of work for not very much time saved.
