### ISSUE TITLE
Better popup or alert system for informative measures to user

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#61]
The status console window should have better functionality for highlighting alert or warning messages in the logs, and/or displaying a summary of all warning messages received. 
INterface details TBD, priority low. "wish list item".

**Comment by semaphoreP** [comment]
Indeed this would be nice, if we had the time to implement this. If someone really wants to do this, they can re-open this issue. Currently, won't fix.
