### ISSUE TITLE
Improved release process automation

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#62]
We need some better automation for official releases. At a minimum there should be tools to:
1. check out a completely clean copy of the repository
2. update the repository revision ID as a string into the gpi_pipeline_version ? 
   -3. Build zip and tar files of the source code-
3. run gpi_compiler to generate the runtime code versions.

**Comment by mperrin** [comment]
Legacy Rejected/wontfix issue migrated from redmine issue tracker. No action desired at this time.
