### ISSUE TITLE
add ability to append new flexure lookup table measurements onto existing table

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#69]
For the flexure measurement code, I think it would be nice to have an ability to easily add new measurements onto an existing table. For instance imagine we're at Gemini and we're trying to map out the flexure there and we already have a rough model, but then we take a bunch of new measurements. It would be nice to just be able to append those as extra rows onto the existing table. This would be optional, set by some new parameter, maybe append_to_existing_table='yes' or something like that.

If you choose to append, it would start by asking the calibration DB for the best available flexure shifts file already present. Then I can imagine it would either: 

1) the primitive opens that existing table, adds all the new records into it, and saves it back out using the prior original file name, or
2) the primitive opens that existing table, copies out all the records from it, then saves both the old and new records into a new file.

Any opinions?

**Comment by mperrin** [comment]
Legacy Rejected/wontfix issue migrated from redmine issue tracker. Originally filed by @mperrin on 2013-04-26

The automated quick wavecal/polcal approach means we have not needed the approach described above. I see no reason to implement this functionality.  Flexure info shown in @swolff9 's recent SPIE paper.
