### ISSUE TITLE
Recipe wavelength_solution#2 using primitive gpi_extract_wavcal_locations.pro

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#70]
Need to evaluate under what circumstances if any it is preferable to use this recipe.

**Comment by mperrin** [comment]
Legacy Rejected/wontfix issue migrated from redmine issue tracker. Originally filed by @jruffio on 2013-04-29

@swolff9 is this recipe even still present today? I presume this issue is very outdated and can just be closed.

**Comment by dsavransky** [comment]
Recovering rm journals for issue:

mperrin: Jerome, can you take a look at this one, please? 

I'm not sure under what circumstances it makes sense to use 'gpi_extract_wavecal2' vs ' gpi_extract_wavecal_locations'. We need to document this as part of the pipeline manual, and make a clear recommendation how typical users should calibrate their data. 

mperrin: I believe that gpi_extract_wavcal_locations.pro is not particularly used by anything right now, there's not any strong reason for it to be, and it should be deprecated and deleted from the pipeline. Does anyone object to this? If so, speak now...

mperrin: Action from 2013-08-02 telecon: Jerome to compare the results of this recipe versus the standard wavecal recipe, by repeating the DRP SW ATP#1 tests using this recipe. 

mperrin: Probably no need to update or work on this reduction recipe, given that Schuyler's new 2D wavecal code is working well. I suggest closing this issue and removing or hiding the "wavelength solution #2" recipe so as not to confuse users. Agreed? 

mperrin: Does anyone have any objection to the following that I suggested 3 weeks ago? Hearing none by the end of today I'm going to close this issue: 

> Probably no need to update or work on this reduction recipe, given that Schuyler's new 2D wavecal code is working well. I suggest closing this issue and removing or hiding the "wavelength solution #2" recipe so as not to confuse users. Agreed?
