### ISSUE TITLE
default recipe editor mode selection

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#71]
It would be nice to have a settings parameter that allows the user to choose which mode the recipe editor loads in, and maybe which set(s) of primitives they are viewing.

In the future, Schuyler plans to make queue the user to select a filename. Although this is fine for the average user, having an automatic 'save and drop in queue' button is very useful for debugging etc. It would be nice to have this button available in the 'Advanced Mode' of the recipe editor.

**Comment by mperrin** [comment]
Legacy Rejected/wontfix issue migrated from redmine issue tracker. No action desired at this time. 

Originally filed by @pi11235 in 2013
