### ISSUE TITLE
Recipe editor - give it an option to reload the primitives config w/out having to close and reload the recipe editor

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#72]
Subject line says it all. For 4 am recompiling at Gemini south...

**Comment by semaphoreP** [comment]
Technically, this seems hard. Given the pipeline is fairly stable at this point, it's probably not worth implementing. The alternative of saving the recipe, closing the recipe editor, rescanning the DRP Config, reopening the recipe editor, and loading the recipe isn't too bad.
