### ISSUE TITLE
additional launcher buttons for at gemini?

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#73]
It could be useful to have launcher buttons to bring up a new gpitv window for the latest cube, or for the latest image.  The use case is you're looking at the most recent cube, and you want to do some stretches or plots or whatever, but every 60 seconds a new image comes in and messes you up. So it would be useful to have a one click button to bring up a new viewer for the current image.

**Comment by mperrin** [comment]
Legacy Rejected/wontfix issue migrated from redmine issue tracker. Originally filed by @mperrin on 2013-11-16

Already working well at Gemini today, no further changes needed at this time.
