### ISSUE TITLE
should encountering an aborted frame in a recipe just print an error message, or pop up an actual dialog message warning? 

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#74]
Subject says it all. Right now an aborted frame in a recipe will just quietly fail that recipe and print the following error text:
###### ##### start of file 2

21:51:42.859     Reducing file: S20131117S0193.fits
21:51:42.920  ERROR: The following file was aborted during the exposure and should be removed from the dataset:/Users/mperrin/data/GPI/Detector/S20131117S0193.fits
Failure
21:51:42.922  ERROR with /Users/mperrin/data/GPI/queue/S20131117S0192-0196_darks_drf.failed.xml. Reduction failed.

This is probably OK but maybe we should have it pop up an error dialog as well?

**Comment by semaphoreP** [comment]
This behavior is ok for now. For GPIES, the database bad file flagging marks these frames as bad anyways. For users manually reduce the data, the error message is clear enough to know what to do to fix the issue.
