### ISSUE TITLE
autoreducer is writing output cubes to wrong directory at Gemini

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#75]
Example: 131117/S20131118S0011_spdc.fits

This is happening at ~ 9 pm Chilean time on Sun Nov 17 (local time) which should be 131118 in Gemini date string land. Clearly there's some piece of code that doesn't know about the 2pm rollover we missed?

**Comment by mperrin** [comment]
Legacy Rejected/wontfix issue migrated from redmine issue tracker. No action desired at this time. 

Three year old issue, I'm sure we fixed this at some point in the last few years and just never updated the old issue tracker.
