### ISSUE TITLE
Launcher window should allow multiple copies of the Recipe Editor, Parser, etc. 

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#76]
You can launch arbitrary n gpitvs, but you can't launch multiple recipe editors or data parsers.  We should make these all behave consistently with numbered sessions, I think.

**Comment by semaphoreP** [comment]
The use case for this is too small to warrant a change to the DRP backbone. Also, one can open more than one recipe editor from the data parser window, so that can be a workaround if really needed.
