### ISSUE TITLE
GPITV launch command line

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#81]
Add a script to launch GPITV from the command line with a file name attached.

**Comment by mperrin** [comment]
Legacy Rejected/wontfix issue migrated from redmine issue tracker. Originally filed by @jchilcote on 2015-01-15

**Comment by dsavransky** [comment]
Recovering rm journals for issue:

mperrin: I don't think a script is needed for this actually. 

unix>   idl -e "gpitv, 'S20131117S0019_spdc.fits'"

You can do idl -e "any one line command" to start IDL and run that command. The IDL will exit as soon as the command finishes so exiting gpitv will close the whole IDL session, but if you don't want that behavior then you just have to start the IDL session ahead of time.
