### ISSUE TITLE
AVPARANG calculation fails on this one file

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#86]
avparang crash on file S20150501S0382. Discussion with Eric indicates qromb is trying to be too precision but this frame is neither going through transit or at the right dec where it moves super fast. Someone should sanity check that this is actually broken.

Error dump:
% Program caused arithmetic error: Floating divide by 0
% Program caused arithmetic error: Floating illegal operand
% QROMB: Too many steps in routine qromb.
% Execution halted at: CALC_AVPARANG      95
   /home/gpiuser/GPI/pipeline/utils/calc_avparang.pro
%                      GPI_UPDATE_WCS_BASIC  233
   /home/gpiuser/GPI/pipeline/utils/gpi_update_wcs_basic.pro
%                      GPI_ASSEMBLE_SPECTRAL_DATACUBE  105
   /home/gpiuser/GPI/pipeline/primitives/gpi_assemble_spectral_datacube.pro
%                      GPIPIPELINEBACKBONE::RUNMODULE  904
   /home/gpiuser/GPI/pipeline/backbone/gpipipelinebackbone__define.pro
%                      GPIPIPELINEBACKBONE::REDUCE  724
   /home/gpiuser/GPI/pipeline/backbone/gpipipelinebackbone__define.pro
%                      GPIPIPELINEBACKBONE::RUN_ONE_RECIPE  616
   /home/gpiuser/GPI/pipeline/backbone/gpipipelinebackbone__define.pro
%                      GPIPIPELINEBACKBONE::RUN_QUEUE  447
   /home/gpiuser/GPI/pipeline/backbone/gpipipelinebackbone__define.pro
%                      GPI_LAUNCH_PIPELINE   99
   /home/gpiuser/GPI/pipeline/backbone/gpi_launch_pipeline.pro
%                      $MAIN$

**Comment by mperrin** [comment]
Legacy issue migrated from redmine issue tracker. Originally filed by @semaphoreP on 2015-05-01 

Probably subsequently fixed by Eric's improvements to the AVPARANG code? @semaphoreP I presume this file is OK in current reprocessing?

**Comment by semaphoreP** [comment]
This indeed has been fixed. I just tested it.
