### ISSUE TITLE
Pol mode sat spot flux measurement needs different configuration at different bands

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpi_pipeline#98]
In particular, the apodizer grids for each band are not aligned perfectly. This might not have been a problem this last run, but for older J band data at least, which was taken with the J-apodizer, the sat spots are rotated about 4-5 degrees from H band. Currently, only the H band positions are hard coded into the primitive. For each apodizer, a different rotation angle should be defined to account for sat spot rotation.

**Comment by mperrin** [comment]
Really this should be tagged to Sebastian but I don't think he is on github yet

**Comment by semaphoreP** [comment]
Pauline has also been working on this so I've added her

**Comment by mperrin** [comment]
Legacy issue migrated from redmine issue tracker. Originally filed by @semaphoreP on 2016-04-01

**Comment by dsavransky** [comment]
Recovering rm journals for issue:

**Comment by tmesposito** [comment]
I've updated the gpi_measure_satellite_spot_flux_pol primitive to better align the flux measurement apertures with the satellite spots. They were previously several pixels off in X and Y, especially for non-H band. The primitive now does the following:
1. Locates sat spots at the correct radial separation in lambda/D for a given apodizer. Based on diffractive grid spacing quoted in Dropbox instrument doc GPI_AMNH_FinalDeliveryBRO.pdf.
2. Locates sat spots at the correct angles for a given apodizer (aligned by eye).
3. Offers option to use 2nd order sat spots for Y and J band.
![jpol_flux_apertures_old_v_new](https://user-images.githubusercontent.com/18746866/43350766-1b1bd4fa-91bf-11e8-8fd0-30ca507c1beb.png)
